[package]
name = "backendproject"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
